## Matrix of Linear Transformation

In [22]:
import numpy as np
from numpy import linalg as la
def T(x,y,z):
    return [x-y+z, 2*x+3*y+(1/2)*z, x+y-2*z]
B1 = np.array([[-1,1,0],[5,-1,2],[1,2,1]])
print("The specified basis for the domain space is ", B1)
B2 = np.array([[1,1,0],[0,0,1],[1,5,2]])
print("The specified basis for the co-domain space is ", B2)
w1 = T(-1,1,0)
w2 = T(5,-1,2)
w3 = T(1,2,1)
print("Evaluating T at the vectors of basis B1: ", w1, w2, w3)
v1 = la.solve(B2.T,w1)
v2 = la.solve(B2.T,w2)
v3 = la.solve(B2.T,w3)
M = np.array([v1,v2,v3])
print("The matrix of the linear transformation is:\n", M.T)

The specified basis for the domain space is  [[-1  1  0]
 [ 5 -1  2]
 [ 1  2  1]]
The specified basis for the co-domain space is  [[1 1 0]
 [0 0 1]
 [1 5 2]]
Evaluating T at the vectors of basis B1:  [-2, 1.0, 0] [8, 8.0, 0] [0, 8.5, 1]
The matrix of the linear transformation is:
 [[-2.75   8.    -2.125]
 [-1.5    0.    -3.25 ]
 [ 0.75   0.     2.125]]


## Simplifying with List Comprehension

In [23]:
import numpy as np

def T(x):
    return [x[0]-x[1]+x[2], 2*x[0]+3*x[1]+(1/2)*x[2], x[0]+x[1]-2*x[2]]

B1 = np.array([[-1,1,0],[5,-1,2],[1,2,1]])
B2 = np.array([[1,1,0],[0,0,1],[1,5,2]])
w = [T(v) for v in B1]

print("Evaluating T at the vectors of basis B1: ", w)
v = np.array([np.linalg.solve(B2.T,w[i]) for i in range(len(w))])

print("The matrix of the linear transformation is:\n", v.T)

Evaluating T at the vectors of basis B1:  [[-2, 1.0, 0], [8, 8.0, 0], [0, 8.5, 1]]
The matrix of the linear transformation is:
 [[-2.75   8.    -2.125]
 [-1.5    0.    -3.25 ]
 [ 0.75   0.     2.125]]


## Find the Linear Transformation if Matrix and Bases are Give

In [24]:
import sympy as sp
from sympy.abc import x,y,a,b

A = sp.Matrix([[2,3],[4,-5]])
B1 = [sp.Matrix([1,-1]), sp.Matrix([1,1])]
B2 = [sp.Matrix([1,0]), sp.Matrix([0,1])]  
T0 = A[0,0]*B2[0] + A[1,0]*B2[1]
T1 = A[0,1]*B2[0] + A[1,1]*B2[1]
print('The images of the ordered basis vectors in B1 under the transformation are', T0, T1)

eq = a*B1[0]+b*B1[1]

c = sp.solve(sp.Matrix([x,y])-eq,[a,b],dict=True)[0]
print("The co-ordinates of the vector (x,y) w.r.t B1 are", c)
t = T0*c[a] + T1*c[b]
print("The linear transformation of T is T(x,y) = ", tuple(t))

The images of the ordered basis vectors in B1 under the transformation are Matrix([[2], [4]]) Matrix([[3], [-5]])
The co-ordinates of the vector (x,y) w.r.t B1 are {a: x/2 - y/2, b: x/2 + y/2}
The linear transformation of T is T(x,y) =  (5*x/2 + y/2, -x/2 - 9*y/2)
